spring:
    application:
        name: personal-financial-behavior-analyzer
    datasource:
        url: jdbc:postgresql://localhost:5432/pfba
        username: pfba_user
        password: pfba_pass

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true


    config:
        import: optional:file:.env[.properties]

server:
    port: 8080

management:
    endpoints:
        web:
            exposure:
                include: health,info

llm:
  gemini:
    api-key: ${GEMINI_API_KEY}

jwt:
    secret: pfba-super-secure-jwt-signing-key-2026-prod-secret
    expiration-ms: 3600000

